[package]
name = "AeP"
description = "Password generator that generates passwords with the use of the SHA-256 hash function."
license = "GPL-3.0"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "3.2.1", features = ["derive"] }
rand = "0.8.5"
sha2 = "0.10.2"
rayon = "1.5.3"
